### ISSUE TITLE
zentao-cn has released 15.0.3

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-zentao#3]
**What type of your feature request?**  

- [x] Add new features
- [x] Improve current features

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by geraintlyu** [comment]
点击登陆按钮的过程中，会遇到/data/wwwroot/zentao/www/data文件夹的权限不够的问题
![zentao-buh](https://user-images.githubusercontent.com/53968450/126023768-cec92d7a-a727-41d3-8229-a1356668983d.png)

请确认data目录是否存在，其权限是什么？www目录的权限是什么？

**Comment by geraintlyu** [comment]
禅道的15.0.3正确！
![zentao-ve](https://user-images.githubusercontent.com/53968450/126023937-0a6f695e-3b4c-486d-9545-948a15c00291.png)
![version-zentao](https://user-images.githubusercontent.com/53968450/126023939-5acd1128-e832-4051-9ae2-b5f754efdc90.png)

**Comment by zengxc-1996** [comment]
![image](https://user-images.githubusercontent.com/63622990/126094502-451837e0-80c3-4032-a170-6795a45fa652.png)

[zentao solution](https://www.zentao.net/ask/38184/9152.html)

**Comment by qiaofeng1227** [comment]
https://www.zentao.net/thread/291536.html
